### ISSUE TITLE
nvim lsp

### ISSUE THREAD

**Issue by dagadbm** [disrupted/dotfiles#2]
Hey!

I saw  you  have  amazing nvim dotfiles in particularly lsp configurations with eslint/prettier  etc.
Have  you thought about creating a plugin to help other  people manage all of this easierly?

Amazing dot files btw, when I have the courage I will try to use zinit as well.

**Comment by disrupted** [comment]
Thanks for your feedback! Sorry, somehow I never replied to your issue. This is out of scope for this repo, I believe this is highly individual what you'd need in your language setup and I encourage you to play tinker with it until you're happy.
